import React, { createContext, useContext, useEffect, useMemo, useState } from 'react'
import { createRoot } from 'react-dom/client'
import { BrowserRouter, Link, NavLink, Route, Routes, useNavigate, useParams, useLocation } from 'react-router-dom'
import { products as initialProducts, categories as initialCategories, formatPrice } from './data'
import { AuthProvider } from './Auth'
import Admin from './Admin'
import './index.css'

const CartContext = createContext(null)
function CartProvider({ children }) {
  const [cart, setCart] = useState(() => JSON.parse(localStorage.getItem('oz-cart') || '[]'))
  const [products, setProducts] = useState(() => { try { return JSON.parse(localStorage.getItem('oz-products')) || initialProducts } catch { return initialProducts } })
  const [categories, setCategories] = useState(() => { try { return JSON.parse(localStorage.getItem('oz-categories')) || initialCategories } catch { return initialCategories } })
  useEffect(() => localStorage.setItem('oz-cart', JSON.stringify(cart)), [cart])
  useEffect(() => localStorage.setItem('oz-products', JSON.stringify(products)), [products])
  useEffect(() => localStorage.setItem('oz-categories', JSON.stringify(categories)), [categories])
  const add = (product) => setCart(items => { const found = items.find(x => x.id === product.id); return found ? items.map(x => x.id === product.id ? {...x, qty: x.qty + 1} : x) : [...items, {...product, qty: 1}] })
  const update = (id, qty) => setCart(items => qty < 1 ? items.filter(x => x.id !== id) : items.map(x => x.id === id ? {...x, qty} : x))
  const total = cart.reduce((sum, x) => sum + x.price * x.qty, 0)
  return <CartContext.Provider value={{cart, add, update, total, count: cart.reduce((s,x)=>s+x.qty,0), products, setProducts, categories, setCategories}}>{children}</CartContext.Provider>
}
function Icon({ children }) { return <span aria-hidden="true" className="text-lg leading-none">{children}</span> }
function ThemeToggle() {
  const [dark, setDark] = useState(() => localStorage.getItem('oz-theme') === 'dark' || (!localStorage.getItem('oz-theme') && matchMedia('(prefers-color-scheme: dark)').matches))
  useEffect(() => { document.documentElement.classList.toggle('dark', dark); localStorage.setItem('oz-theme', dark ? 'dark' : 'light') }, [dark])
  return <button className="rounded-full p-2 hover:bg-stone-100 dark:hover:bg-zinc-800" onClick={() => setDark(!dark)} aria-label="Changer de thème"><i className="fi fi-rr-moon" style={{fontSize: 20}}></i></button>
}
function Header() { const { count } = useContext(CartContext); const [open, setOpen] = useState(false)
  return <header className="sticky top-0 z-20 border-b border-stone-200/80 bg-paper/95 backdrop-blur dark:border-zinc-800/80 dark:bg-zinc-950/95"><div className="shell flex h-20 items-center justify-between gap-6"><Link to="/" className="font-display text-xl font-bold">Original<span className="text-sage">Zone</span></Link><nav className="hidden items-center gap-7 text-sm font-medium md:flex"><NavLink to="/catalogue" className={({isActive}) => isActive ? 'text-sage' : 'hover:text-sage'}>Catalogue</NavLink><a href="#approche" className="hover:text-sage">Notre approche</a></nav><div className="flex items-center gap-2"><ThemeToggle/><Link to="/compte" className="hidden rounded-full p-2 hover:bg-stone-100 dark:hover:bg-zinc-800 sm:block" aria-label="Mon compte"><i className="fi fi-rr-user" style={{fontSize: 20}}></i></Link><Link to="/panier" className="relative rounded-full p-2 hover:bg-stone-100 dark:hover:bg-zinc-800" aria-label="Panier"><i className="fi fi-rr-shopping-cart" style={{fontSize: 20}}></i>{count > 0 && <span className="absolute right-0 top-0 flex h-4 min-w-4 items-center justify-center rounded-full bg-sage px-1 text-[10px] font-bold text-white">{count}</span>}</Link><button className="p-2 md:hidden" onClick={() => setOpen(!open)} aria-label="Menu"><i className="fi fi-rr-menu-burger" style={{fontSize: 20}}></i></button></div></div>{open && <nav className="shell flex flex-col gap-4 pb-5 text-sm md:hidden"><Link to="/catalogue">Catalogue</Link><Link to="/compte">Mon compte</Link></nav>}</header>
}
function ProductCard({ product }) { const { add } = useContext(CartContext); return <article className="group"><Link to={`/produit/${product.id}`} className="block overflow-hidden rounded-2xl bg-stone-100 dark:bg-zinc-900"><img src={product.image} alt={product.name} className="aspect-[4/5] w-full object-cover transition duration-500 group-hover:scale-[1.03]" loading="lazy"/><div className="flex items-center justify-between p-3"><span className="text-xs text-stone-500 dark:text-stone-400">{product.category}</span><span className="text-xs text-sage">{product.stock ? 'Disponible' : 'Rupture'}</span></div></Link><div className="flex items-start justify-between gap-3 pt-4"><div><h3 className="font-display font-semibold">{product.name}</h3><p className="mt-1 text-sm text-stone-500 dark:text-stone-400">{formatPrice(product.price)}</p></div><button disabled={!product.stock} onClick={() => add(product)} className="button-secondary min-h-9 px-3 text-xs disabled:cursor-not-allowed disabled:opacity-40">Ajouter</button></div></article> }
function Home() { const { products } = useContext(CartContext); return <><section className="shell grid min-h-[620px] items-center gap-12 py-14 lg:grid-cols-[1fr_1.05fr]"><div className="max-w-xl"><p className="eyebrow mb-6">Objets choisis, espaces habités</p><h1 className="font-display text-5xl font-semibold leading-[1.08] tracking-[-0.04em] sm:text-7xl">Ce qui compte trouve sa place.</h1><p className="mt-7 max-w-md text-lg leading-8 text-stone-600 dark:text-stone-300">Du mobilier pensé pour durer, livré simplement chez vous.</p><div className="mt-9 flex flex-wrap gap-3"><Link to="/catalogue" className="button-primary">Découvrir la collection</Link><a href="#approche" className="button-secondary">Notre approche</a></div></div><div className="relative"><img src="https://picsum.photos/seed/fauteuil-lumineux/800/1000" alt="Fauteuil dans un intérieur lumineux" className="aspect-[4/5] w-full rounded-[2rem] object-cover sm:aspect-[5/4] lg:aspect-[4/5]"/><div className="surface absolute bottom-5 left-5 max-w-[220px] p-4"><p className="text-sm font-semibold">Livraison soignée</p><p className="mt-1 text-xs leading-5 text-stone-500 dark:text-stone-400">Chaque pièce est préparée et suivie jusqu'à votre porte.</p></div></div></section><section id="approche" className="border-y border-stone-200 py-20 dark:border-zinc-800"><div className="shell grid gap-12 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Notre approche</p><h2 className="mt-4 max-w-sm font-display text-3xl font-semibold tracking-tight">Acheter moins, choisir mieux.</h2></div><div className="grid gap-8 sm:grid-cols-3"><div><span className="text-2xl text-sage">01</span><h3 className="mt-4 font-semibold">Des matières justes</h3><p className="mt-2 text-sm leading-6 text-stone-500 dark:text-stone-400">Nous privilégions les matériaux qui vieillissent bien.</p></div><div><span className="text-2xl text-sage">02</span><h3 className="mt-4 font-semibold">Une sélection courte</h3><p className="mt-2 text-sm leading-6 text-stone-500 dark:text-stone-400">Chaque objet est retenu pour son usage et sa présence.</p></div><div><span className="text-2xl text-sage">03</span><h3 className="mt-4 font-semibold">Un service humain</h3><p className="mt-2 text-sm leading-6 text-stone-500 dark:text-stone-400">Une question avant ou après l'achat ? Nous répondons.</p></div></div></div></section><section className="shell py-20"><div className="flex items-end justify-between gap-5"><div><p className="eyebrow">La collection</p><h2 className="mt-3 font-display text-3xl font-semibold">Quelques essentiels</h2></div><Link to="/catalogue" className="text-sm font-semibold text-sage">Voir tout <span aria-hidden="true">→</span></Link></div><div className="mt-9 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{products.map(p => <ProductCard key={p.id} product={p}/>)}</div></section></> }
function Catalogue() { const { products, categories } = useContext(CartContext); const [query,setQuery]=useState(''); const [category,setCategory]=useState('Toutes'); const [available,setAvailable]=useState(false); const filtered=products.filter(p => (!query || `${p.name} ${p.brand}`.toLowerCase().includes(query.toLowerCase())) && (category==='Toutes'||p.category===category) && (!available||p.stock>0)); return <main className="shell py-12"><div className="max-w-2xl"><p className="eyebrow">Catalogue</p><h1 className="mt-3 font-display text-4xl font-semibold tracking-tight sm:text-5xl">Des pièces pour vivre avec.</h1></div><div className="mt-10 flex flex-col gap-4 border-b border-stone-200 pb-6 lg:flex-row lg:items-center lg:justify-between"><label className="flex items-center gap-3 rounded-full border border-stone-300 px-4 py-2 dark:border-zinc-700 lg:w-80"><i className="fi fi-rr-search" style={{fontSize: 20}}></i><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Rechercher" className="w-full bg-transparent text-sm outline-none"/></label><div className="flex flex-wrap items-center gap-2">{['Toutes', ...categories].map(c=><button key={c} onClick={()=>setCategory(c)} className={`rounded-full px-4 py-2 text-sm ${category===c?'bg-sage text-white':'border border-stone-300 dark:border-zinc-700'}`}>{c}</button>)}<label className="ml-2 flex items-center gap-2 text-sm"><input type="checkbox" checked={available} onChange={e=>setAvailable(e.target.checked)} className="accent-sage"/> En stock</label></div></div><p className="mt-7 text-sm text-stone-500 dark:text-stone-400">{filtered.length} article{filtered.length>1?'s':''}</p><div className="mt-7 grid gap-x-5 gap-y-12 sm:grid-cols-2 lg:grid-cols-4">{filtered.map(p=><ProductCard key={p.id} product={p}/>)}</div></main> }
function ProductPage() { const {id}=useParams(); const {products, add}=useContext(CartContext); const product=products.find(p=>p.id===id)||products[0]; const [size,setSize]=useState(product.sizes[0]); return <main className="shell py-10"><Link to="/catalogue" className="text-sm text-stone-500 hover:text-sage">← Retour au catalogue</Link><div className="mt-8 grid gap-10 lg:grid-cols-[1.05fr_.95fr]"><div><img src={product.image} alt={product.name} className="aspect-square w-full rounded-2xl object-cover"/></div><div className="flex flex-col justify-center lg:pl-8"><p className="eyebrow">{product.category} / {product.brand}</p><h1 className="mt-4 font-display text-4xl font-semibold tracking-tight sm:text-5xl">{product.name}</h1><p className="mt-4 text-xl">{formatPrice(product.price)}</p><p className="mt-7 max-w-md leading-7 text-stone-600 dark:text-stone-300">{product.description}</p><div className="mt-8 border-y border-stone-200 py-6 dark:border-zinc-800"><p className="text-sm font-semibold">Format</p><div className="mt-3 flex gap-2">{product.sizes.map(s=><button key={s} onClick={()=>setSize(s)} className={`rounded-full border px-4 py-2 text-sm ${size===s?'border-sage bg-sage/10 text-sage':'border-stone-300 dark:border-zinc-700'}`}>{s}</button>)}</div></div><div className="mt-6 flex items-center gap-3 text-sm"><span className="text-sage">●</span>{product.stock ? `${product.stock} pièces disponibles` : 'Actuellement indisponible'}</div><button onClick={()=>add(product)} disabled={!product.stock} className="button-primary mt-8 w-full disabled:opacity-40">Ajouter au panier</button><p className="mt-4 text-center text-xs text-stone-500">Paiement sécurisé · Retours sous 30 jours</p></div></div><section className="mt-20 max-w-2xl border-t border-stone-200 pt-10 dark:border-zinc-800"><h2 className="font-display text-2xl font-semibold">Avis clients</h2><p className="mt-4 text-stone-600 dark:text-stone-300">★★★★★ <span className="ml-2">{product.rating} sur {product.reviews} avis</span></p><p className="mt-6 leading-7 text-stone-600 dark:text-stone-300">“Une pièce très bien finie. Elle s'intègre naturellement dans notre salon.”</p></section></main> }
function Cart() { const {cart,update}=useContext(CartContext); const navigate=useNavigate(); return <main className="shell py-12"><h1 className="font-display text-4xl font-semibold">Votre panier</h1>{!cart.length?<div className="surface mt-10 p-10 text-center"><p className="text-stone-500">Votre panier est encore vide.</p><Link to="/catalogue" className="button-primary mt-6">Voir la collection</Link></div>:<div className="mt-10 grid gap-10 lg:grid-cols-[1fr_360px]"><div className="space-y-4">{cart.map(item=><div key={item.id} className="surface flex gap-4 p-4"><img src={item.image} alt="" className="h-28 w-24 rounded-xl object-cover"/><div className="flex flex-1 flex-col justify-between"><div><h2 className="font-semibold">{item.name}</h2><p className="mt-1 text-sm text-stone-500">{formatPrice(item.price)}</p></div><div className="flex items-center justify-between"><label className="text-sm">Quantité <select value={item.qty} onChange={e=>update(item.id,Number(e.target.value))} className="ml-2 rounded-lg border border-stone-300 bg-transparent p-1 dark:border-zinc-700">{[1,2,3,4,5].map(n=><option key={n}>{n}</option>)}</select></label><button onClick={()=>update(item.id,0)} className="text-sm text-stone-500 underline">Retirer</button></div></div></div>)}</div><aside className="surface h-fit p-6"><h2 className="font-display text-xl font-semibold">Résumé</h2><div className="mt-6 flex justify-between border-b border-stone-200 pb-4 text-sm dark:border-zinc-800"><span>Sous-total</span><span>{formatPrice(cart.reduce((sum, x) => sum + x.price * x.qty, 0))}</span></div><div className="mt-4 flex justify-between text-sm"><span>Livraison</span><span>Calculée au checkout</span></div><button onClick={()=>navigate('/checkout')} className="button-primary mt-7 w-full">Passer la commande</button></aside></div>}</main> }
function Checkout() { const {total}=useContext(CartContext); const [done,setDone]=useState(false); if(done)return <main className="shell py-24 text-center"><div className="mx-auto max-w-lg"><span className="text-5xl text-sage">✓</span><h1 className="mt-6 font-display text-4xl font-semibold">Commande confirmée</h1><p className="mt-4 leading-7 text-stone-600 dark:text-stone-300">Merci. Un email de confirmation et de suivi vous sera envoyé.</p><Link to="/catalogue" className="button-primary mt-8">Continuer mes achats</Link></div></main>; return <main className="shell py-12"><div className="max-w-2xl"><p className="eyebrow">Checkout sécurisé</p><h1 className="mt-3 font-display text-4xl font-semibold">Finaliser votre commande</h1></div><form onSubmit={e=>{e.preventDefault();setDone(true)}} className="mt-10 grid gap-10 lg:grid-cols-[1fr_360px]"><div className="space-y-5"><div className="surface p-6"><h2 className="font-display text-xl font-semibold">Vos coordonnées</h2><div className="mt-5 grid gap-4 sm:grid-cols-2"><Field label="Prénom"/><Field label="Nom"/><Field label="Email" type="email"/><Field label="Adresse"/><Field label="Ville"/><Field label="Code postal"/></div></div><div className="surface p-6"><h2 className="font-display text-xl font-semibold">Paiement</h2><p className="mt-2 text-sm text-stone-500">Carte bancaire, PayPal et portefeuilles mobiles via un prestataire PCI-DSS.</p><Field label="Numéro de carte"/><div className="mt-4 grid gap-4 sm:grid-cols-2"><Field label="Expiration"/><Field label="Cryptogramme"/></div></div></div><aside className="surface h-fit p-6"><div className="flex justify-between text-sm"><span>Total</span><strong>{formatPrice(total)}</strong></div><button className="button-primary mt-7 w-full">Payer en sécurité</button><p className="mt-4 text-center text-xs text-stone-500">Vos données sont chiffrées. Aucun paiement réel n'est exécuté dans cette démo.</p></aside></form></main> }
function Field({label,type='text'}) { return <label className="block text-sm font-medium">{label}<input required type={type} className="mt-2 min-h-11 w-full rounded-xl border border-stone-300 bg-transparent px-3 dark:border-zinc-700"/></label> }
function Account() { return <main className="shell py-12"><p className="eyebrow">Espace client</p><h1 className="mt-3 font-display text-4xl font-semibold">Bonjour, Camille.</h1><div className="mt-10 grid gap-5 md:grid-cols-3"><div className="surface p-6 md:col-span-2"><h2 className="font-display text-xl font-semibold">Dernières commandes</h2><div className="mt-6 flex items-center justify-between border-t border-stone-200 pt-5 text-sm dark:border-zinc-800"><span><strong>OZ-1048</strong><br/><span className="text-stone-500">12 juin 2025</span></span><span className="rounded-full bg-sage/10 px-3 py-1 text-xs font-semibold text-sage">En préparation</span><strong>{formatPrice(690)}</strong></div></div><div className="surface p-6"><h2 className="font-display text-xl font-semibold">Mes informations</h2><p className="mt-5 text-sm leading-7 text-stone-500">camille@example.com<br/>12 rue des Lilas<br/>75011 Paris</p><button className="mt-5 text-sm font-semibold text-sage">Modifier mes données</button></div></div></main> }
function Footer(){return <footer className="border-t border-stone-200 py-10 dark:border-zinc-800"><div className="shell flex flex-col justify-between gap-5 text-sm text-stone-500 sm:flex-row"><span> 2025 OriginalZone</span><span>Paiement sécurisé · Livraison suivie · Retours 30 jours</span><span><a href="https://www.flaticon.com/uicons" target="_blank" rel="noopener noreferrer" className="text-stone-500">Icones par Flaticon UIcons</a></span></div></footer>}
function AdminRoute() { const { products, setProducts, categories, setCategories } = useContext(CartContext); return <Admin products={products} setProducts={setProducts} categories={categories} setCategories={setCategories}/> }
function App(){return <AuthProvider><CartProvider><Header/><Routes><Route path="/" element={<Home/>}/><Route path="/catalogue" element={<Catalogue/>}/><Route path="/produit/:id" element={<ProductPage/>}/><Route path="/panier" element={<Cart/>}/><Route path="/checkout" element={<Checkout/>}/><Route path="/compte" element={<Account/>}/><Route path="/admin" element={<AdminRoute/>}/></Routes><Footer/></CartProvider></AuthProvider>}
createRoot(document.getElementById('root')).render(<BrowserRouter><App/></BrowserRouter>)
